// frontend/react/src/components/RightNav.js
import { IconButton } from '@mui/material'
import LoginIcon from '@mui/icons-material/Login';
import SettingIcon from '@mui/icons-material/Settings'
import PersonIcon from '@mui/icons-material/Person'
import HomeIcon from '@mui/icons-material/Home';
import { useNavigate } from "react-router-dom"
import { useState } from "react"
import Axios from "axios"

function RightNav(props){
  const [name,] = useState(sessionStorage.getItem("name"))
  const [token,] = useState(sessionStorage.getItem("token"))
  const [page,] = useState(props.page)
  const nav = useNavigate()
  
  function logout(){
    Axios.delete(props.backendlink + "logout",{ data: {name, token}} )
    .then((res) => {
      console.log(res.data)
      sessionStorage.clear()
      //instead of window.location.reload() in case not at homepage
      //using nav required to pass props like url over
      window.location.assign("/") 
    })
    .catch((err)=>{
      console.log(err)
      alert("TRY AGAIN LATER")
    })
  }
  
  function navTo(){
    if(page === "login"){
      nav("/setting")
    }else if(page === "home"){
      nav('/profile')
    }else{
      nav("/")
    }
  }

  return(
    <div className="rightContainer">
      <IconButton aria-label="delete" size="large" onClick={navTo} className="button">
        {page === "login" ? <SettingIcon fontSize="inherit" /> 
          : page === "setting" ? <LoginIcon fontSize="inherit" /> 
          :  page === "home" ?  <PersonIcon fontSize="inherit" />
          : <HomeIcon fontSize="inherit" />
        }
      </IconButton>
      {page === "home" || page === "profile" ? 
        <button type="button" onClick={logout} className="button">
          Logout
        </button> 
        : <></>
      }
    </div>
  )
}

export default RightNav

// frontend/svelte/src/components/RightNav.svelte
<script>
  import {navigate} from "svelte-routing";
  import IconButton, { Icon } from '@smui/icon-button';
  import '@smui/icon-button/*';
  

  export let backendlink = ""
  export let page = ""
  let name = sessionStorage.getItem("name")
  let token = sessionStorage.getItem("token")

  function logout(){
    fetch(backendlink+"logout", {
      method: "DELETE",
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: name,
        token: token
      })
    })
    .then(response => response.json())
    .then(data => {
      if(data.check){
        sessionStorage.clear()
        //instead of window.location.reload() in case not at homepage
        //using nav required to pass props like backendlink over
        window.location.assign("/") 
      }
    })
    .catch((err) =>{
      console.log(err)
      alert("TRY AGAIN LATER")
    })
  }

  function navTo(){
    if(page === "login"){
      navigate("/setting")
    }else if(page === "home"){
      navigate('/profile')
    }else{
      navigate("/")
    }
  }
</script>

<main>
  <div class="rightContainer" >
    {#if page === "login"}
      <button class="transparent-button" on:click={navTo}>
        <i class="fas fa-cog"></i>
      </button>
    {:else if page === "setting"}
      <button class="transparent-button" on:click={navTo}>
        <i class="fas fa-sign-in-alt"></i>
      </button>
    {:else if page === "home"}
      <button class="transparent-button" on:click={navTo}>
        <i class="fas fa-user"></i>
      </button>
    {:else}
      <button class="transparent-button" on:click={navTo}>
        <i class="fas fa-home"></i>
      </button>
    {/if}

    {#if page === "home" || page === "profile"}
      <button type="button" on:click={logout} class="button">
        Logout
      </button> 
    {/if}
  </div>
</main>
