// frontend/svelte/src/components/login.svelte
<script>
  import {navigate} from "svelte-routing"
  import RightNav from "./RightNav.svelte"

  export let backendlink = ""
  let name 
  let password

  function loginForm() {
    fetch(backendlink + "login", {
      method: "POST",
      headers: {       
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: name,
        password: password,
        device: "tester"
      })
    })
    .then(response => response.json())
    .then(data => {
      if(data.check){
        sessionStorage.setItem("token", data.token)
        sessionStorage.setItem("name",name)
        window.location.reload()
      }else{
        alert(data.result)
      }
      })
      .catch((err) =>{
        console.log(err)
        alert("TRY AGAIN LATER")
      })
  }

  function createForm(){
    navigate("/create")
  }

</script>

<main>
  <RightNav backendlink={backendlink} page="login" />
  <div class="centerDiv">
    <span>Login</span>
    <form on:submit|preventDefault={loginForm} class="info">
      <div class="form-group">
        <label for="name" class="text-muted mb-1">
          Name:
        </label>
        <input on:change={(e) => {name = e.target.value}} id="name" name="name" class="form-control" type="text" placeholder="Name" autoComplete="off" />
        </div>
      <div class="form-group">
        <label for="password" class="text-muted mb-1">
          Password:
        </label>
        <input on:change={(e) => {password = e.target.value}} id="password" name="password" class="form-control" type="password" placeholder="Password" />
      </div>
      <button type="submit" class="formButton2 py-3 mt-4 btn btn-lg btn-success btn-block">
        Login
      </button>
      <button type="button" class="formButton2 py-3 mt-4 btn btn-lg btn-success btn-block" on:click={createForm}>
        Sign Up
      </button> 
      
    </form>
  </div>
</main>

<style>

</style>

// frontend/react/src/components/Login.js
import React, { useState } from "react"
import Page from "./Page"
import Axios from "axios" //to help send of request
import { useNavigate } from "react-router-dom"
import RightNav from "./RightNav"

function Login(props) {
  const [name, setName] = useState("")
  const [password, setPassword] = useState("")

  const nav = useNavigate()

  function loginForm(e) {
    e.preventDefault()
    Axios.post(props.backendlink + "login", { name, password, device:"react" }) //unable to get device info
    .then((res)=>{
      if (!res.data.check) {
        alert(res.data.result)
      } else {
        sessionStorage.setItem("token", res.data.token)
        sessionStorage.setItem("name",name)
        props.setToken(sessionStorage.getItem("token"))
        nav("/")
      }
    })
    .catch((err)=>{
      console.log(err)
      alert("TRY AGAIN LATER")
    })
  }

  function createForm(){
    nav("/create")
  }

  return (
    <Page wid={true} title="">
      <RightNav page={'login'} backendlink={props.backendlink}/>
      <div className="centerDiv">
        <span>Login</span>
        <form onSubmit={loginForm} className="info">
          <div className="form-group">
            <label htmlFor="name" className="text-muted mb-1">
              Name:
            </label>
            <input onChange={(e) => setName(e.target.value)} id="name" name="name" className="form-control" type="text" autoComplete="off" />
          </div>
          <div className="form-group">
            <label htmlFor="password" className="text-muted mb-1">
              Password:
            </label>
            <input onChange={(e) => setPassword(e.target.value)} id="password" name="password" className="form-control" type="password" />
          </div>
          <button type="submit" className="formButton2 py-3 mt-4 btn btn-lg btn-success btn-block">
            Login
          </button>
          <button type="button" onClick={createForm} className="formButton2 py-3 mt-4 btn btn-lg btn-success btn-block">
            Sign Up
          </button> 
        </form>
      </div>
    </Page>
  )
}

export default Login
