// frontend/svelte/src/components/Profile.svelte
<script>
  import { onMount } from "svelte";
  import RightNav from "./RightNav.svelte";
  
  export let backendlink = ""
  let name = sessionStorage.getItem("name")
  let token = sessionStorage.getItem("token")

  let password = ""
  let newPassword = ""
  let email
  let dob = ""
  let gender = ""

  onMount(() => { 
    fetch(backendlink+"profile", {
      method: "POST",
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: name,
        token: token
      })
    })
    .then(response => response.json())
    .then(data => {
      if(data.check){
        const result = data.result[0]
        email = result["email"]

        if(result["DOB"] != null){
          let DOBDate = new Date(result["DOB"])
          dob = `${DOBDate.getFullYear()}-${("0" + (DOBDate.getMonth() + 1)).slice(-2)}-${("0" + DOBDate.getDate()).slice(-2)}`
        }
      }
    })
    .catch((err) =>{
      console.log(err)
      alert("TRY AGAIN LATER")
    })
  })


  function emptyForm(){
    password = ""
    newPassword = ""
  }
  

  function editForm(){
    fetch(backendlink+"updateProfile", {
      method: "PATCH",
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: name,
        password: password,
        newPassword, newPassword,
        email: email,
        dob: dob,
        gender: gender,
        token: token
      })
    })
    .then(response => response.json())
    .then(data => { 
      alert(data.result)
      emptyForm()
    })
    .catch((err) =>{
      console.log(err)
      alert("TRY AGAIN LATER")
    })
  }
</script>

<main>
  <RightNav backendlink={backendlink} page="profile" />
  <div class="centerDiv">
    <h1>{name}</h1>
    <form on:submit|preventDefault={editForm} class="info">

    <div class="form-group">
      <label  for="password"  class="text-muted mb-1">
        Password:
      </label>
      <input value={password} on:change={(e) => password = e.target.value} id="password" name="password" class="form-control" type="password" placeholder="Password" required/>
    </div>

    <div class="form-group">
      <label for="newPassword" class="text-muted mb-1">
        New Password:
      </label>
      <input value={newPassword} on:change={(e) => newPassword = e.target.value} id="newPassword" name="newPassword" class="form-control" type="password" placeholder="New Password"/>
    </div>

    <div class="form-group">
        <label for="email" class="text-muted mb-1">
          Email:
        </label>
        <input value={email} on:change={(e) => email = e.target.value} id="email" name="email" class="form-control" type="text" placeholder="Email" required /> 
      </div>

      <div class="form-group">
        <label for="dob" class="text-muted mb-1">
          Dob:
        </label>
        <input value={dob} on:change={(e) => dob = e.target.value} id="dob" name="dob" class="form-control" type="date" placeholder="Dob" />
      </div>

      <div class="form-group">
        <label for="gender" class="text-muted mb-1">
          Gender:
        </label>
        <select value={gender} on:change={e => gender = e.target.value} id="gender" name="gender">
          <option value="">Prefer not to say</option>
          <option value="Male">Male</option>
          <option value="Female">Female</option>
          <option value="Others">Others</option>
        </select>
      </div>
      <button type="submit" class="formButton py-3 mt-4 btn btn-lg btn-success btn-block">
        Update
      </button>
    </form>
  </div>
</main>

// frontend/react/src/components/Profile.js
import { useEffect, useState } from "react"
import Page from "./Page"
import RightNav from "./RightNav"
import Axios from "axios"

function Profile(props){
  const [name, ] = useState(sessionStorage.getItem("name"))
  const [token, ] = useState(sessionStorage.getItem("token"))

  const [password, setPassword] = useState("")
  const [newPassword, setNewPassword] = useState("")
  const [email, setEmail] = useState("")
  const [dob, setDob] = useState("")
  const [gender, setGender] = useState("")

  useEffect(()=>{
    Axios.post(props.backendlink + "profile", { name, token })
    .then((res) => {
      const result = res.data.result[0]
      setEmail(result["email"])
      if(result["DOB"] !== null){
        let DOBDate = new Date(result["DOB"])
        let formatDate = `${DOBDate.getFullYear()}-${("0" + (DOBDate.getMonth() + 1)).slice(-2)}-${("0" + DOBDate.getDate()).slice(-2)}`

        setDob(formatDate)
      }
      if(result["gender"] !== null){
        setGender(result["gender"])
      }
    })
    .catch((err) =>{
      console.log(err)
      alert("TRY AGAIN LATER")
    })
  },[name,token,props.backendlink])

  function emptyForm(pwOnly){
    setPassword("")
    if(!pwOnly){
      setNewPassword("")
    }
  }

  function editForm(e){
    e.preventDefault()
    Axios.patch(props.backendlink + "updateProfile", { name, password, newPassword, email, dob, gender, token })
    .then((res) => {
      alert(res.data.result)
      emptyForm(res.data.check)
    })
    .catch((err) =>{
      console.log(err)
      alert("TRY AGAIN LATER")
    })
  }

  return (
    <Page wid={true} title="">
      <RightNav page={'profile'} backendlink={props.backendlink}/>
      <div className="centerDiv">
        <h1>{name}</h1>
        <form onSubmit={editForm} className="info">

        <div className="form-group">
          <label htmlFor="password" className="text-muted mb-1">
            Password:
          </label>
          <input value={password} onChange={(e) => setPassword(e.target.value)} id="password" name="password" className="form-control" type="password" required/>
        </div>

        <div className="form-group">
          <label htmlFor="newPassword" className="text-muted mb-1">
            New Password:
          </label>
          <input value={newPassword} onChange={(e) => setNewPassword(e.target.value)} id="newPassword" name="newPassword" className="form-control" type="password"/>
        </div>

        <div className="form-group">
            <label htmlFor="email" className="text-muted mb-1">
              Email:
            </label>
            <input value={email} onChange={(e) => setEmail(e.target.value)} id="email" name="email" className="form-control" type="text" required /> 
          </div>

          <div className="form-group">
            <label htmlFor="dob" className="text-muted mb-1">
              Dob:
            </label>
            <input value={dob} onChange={(e) => setDob(e.target.value)} id="dob" name="dob" className="form-control" type="date" />
          </div>

          <div className="form-group">
            <label htmlFor="gender" className="text-muted mb-1">
              Gender:
            </label>
            <select value={gender} onChange={e => setGender(e.target.value)} id="gender" name="gender" className="form-control">
              <option value="">Prefer not to say</option>
              <option value="Male">Male</option>
              <option value="Female">Female</option>
              <option value="Others">Others</option>
            </select>
          </div>

          <button type="submit" className="formButton py-3 mt-4 btn btn-lg btn-success btn-block">
            Update
          </button>
        </form>
      </div>
    </Page>
  )

}

export default Profile
