// frontend/svelte/src/App.svelte
<script>
  import { Router, Route } from "svelte-routing";

	import Loading from "./components/Loading.svelte";
	import NotFound from "./components/NotFound.svelte";

	import Login from "./components/login.svelte";
  import Create from "./components/Create.svelte";

  import Home from "./components/Home.svelte";
	import Profile from "./components/Profile.svelte";
  import Setting from "./components/Setting.svelte";

  let loaded = true
	let loggedIn = false

	let ipaddress = "localhost"
	let port = "3000"
	let backendlink = `http://${ipaddress}:${port}/`

	let token = sessionStorage.getItem("token")
	let name = sessionStorage.getItem("name")

	function userAuth() {
		fetch(backendlink+"profile", {
      method: "POST",
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: name,
				token: token
      })
    })
		.then(response => response.json())
    .then(data => { 
			const dataName = data.result[0]["name"]
			if(name && dataName.toLowerCase() === name.toLowerCase() && !(dataName === name)){
				sessionStorage.setItem("name", dataName)
				name = dataName
			}
			loggedIn = data.check
			loaded = true
		})
		.catch((err) =>{
      console.log(err)
			loaded = true
    })
	}
	
	if(token){
		loaded = false
		userAuth()
	}

	function handleIP(event){
    ipaddress = event.detail["ipaddress"]
		port = event.detail["port"]
		backendlink = event.detail["backendlink"]
  }

</script>


<Router>
	{#if loaded}
		{#if loggedIn}
			<Route path={"/"}>
				<Home backendlink={backendlink} />
			</Route>
			<Route path={"/profile"}>
				<Profile backendlink={backendlink} />
			</Route>
			<Route component={NotFound} />

		{:else}
			<Route path={"/"}>
				<Login backendlink={backendlink}/>
			</Route>
			<Route path={"/create"}>
				<Create backendlink={backendlink}/>
			</Route>
			<Route path={"/setting"}>
				<Setting on:ipChange={handleIP}/>
			</Route>
			<Route component={NotFound} />
		{/if}
	
	{:else}
		<Route component={Loading} />
	{/if}
</Router>

// frontend/react/src/App.js
import './App.css';
import React, { useState, useEffect } from "react"
import { BrowserRouter , Routes, Route} from "react-router-dom" //to nav -- 
import Axios from "axios"

import Login from "./components/Login"
import Setting from "./components/Setting"
import Create from "./components/Create"
import Home from "./components/Home"
import Profile from "./components/Profile"
import NotFound from './components/NotFound'
import Loading from './components/Loading'

function App() {
  const [ipa, setApi] = useState("localhost")
  const [port, setPort] = useState("3000")
  const backendlink = `http://${ipa}:${port}/`
  const [loggedIn, setLoggedIn] = useState(false)
  const [name, setName] = useState(sessionStorage.getItem("name"))
  const [token, setToken] = useState(sessionStorage.getItem("token"))
  const [loaded, isloaded] = useState(false)

  useEffect(()=>{
    if(token){
      setName(sessionStorage.getItem("name"))
    }else{
      setName("")
      isloaded(true)
    }
  },[token])

  function userAuth() {
    Axios.post(backendlink + "profile", { name, token })
    .then((res) => {
      
      const dataName = res.data.result[0]["name"]
      if(name && dataName.toLowerCase() === name.toLowerCase() && !(dataName === name)){
        sessionStorage.setItem("name", dataName)
        setName(dataName)
      }

      setLoggedIn(res.data.check)
      isloaded(true)
    })
    .catch((err)=>{
      console.log(err)
      isloaded(true)
    })
  }

  if (token) {
    userAuth()
  }
  return (
    <BrowserRouter>
      { loaded ? 
        loggedIn ? 
        (
          <Routes>
            <Route exact path="/" element={<Home backendlink={backendlink}/>} />
            <Route exact path="/profile" element={<Profile backendlink={backendlink} />} />
            <Route path="*" element={<NotFound />} />
          </Routes>
        ) : (
          <Routes>
            <Route exact path="/"  element={<Login backendlink={backendlink} setToken={setToken}/>} />
            <Route exact path='/create' element={<Create backendlink={backendlink} setToken={setToken}/>} />
            <Route exact path="/setting" element={<Setting setApi={setApi} setPort={setPort}/> } />
            <Route path="*" element={<NotFound />} />
          </Routes>
        ) : (
          <Routes>
            <Route path="*" element={<Loading/>} />
          </Routes>
        )
      }
    </BrowserRouter>
  );
}

export default App;
